org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=easy_hammers
mod_name=Easy Hammers
mod_license=GNU GENERAL PUBLIC LICENSE Version 3
mod_version=7.0.3
mod_group_id=net.easyhammers
mod_authors=Yigit Guven
mod_description=Adds pickaxe-style tools that effortlessly break a 3x3 area.
